name: todoapp
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.2

  sqflite:
  path:
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:


flutter:

  uses-material-design: true

  assets:
    - assets/images/
